# Generated by Django 3.1.7 on 2021-03-17 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipeingredient_unit_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='display_amount',
        ),
    ]
