# Generated by Django 3.1.7 on 2021-03-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210320_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='directions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
